name:                generic-inference
version:             0.1.0.0
github:              "alexknight0/generic-inference"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexknight0/generic-inference#readme>

dependencies:
- base >= 4.7 && < 5
- time

# Data structures
- algebraic-graphs
- bimap
- containers
- PSQueue
- parsec
- extra

# Join Tree Diagrams
- text
- boxes
- pretty-simple
- colour
- filepath
- diagrams
- diagrams-lib
- diagrams-svg
- diagrams-rasterific
- SVGFonts

# Multi-threading
- parallel

# Distributed Computation
- distributed-process
- network-transport
- network-transport-tcp
- strict-concurrency
- deepseq
- binary
- hashable

# Matrices
- array
- vector-th-unbox
- massiv
- matrix

# Testing & Benchmarking
- criterion
- probability
- dijkstra-simple
- hedgehog
- random

# Testing & Benchmarking (FFT)
- fft
- carray
- vector


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
  - DuplicateRecordFields
  - NoFieldSelectors
  - OverloadedRecordDot

executables:
  generic-inference-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-inference
    when:
      - condition: false
        other-modules: Paths_generic-inference
    default-extensions:
    - DuplicateRecordFields
    - NoFieldSelectors
    - OverloadedRecordDot

tests:
  generic-inference-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-inference
    default-extensions:
    - DuplicateRecordFields
    - NoFieldSelectors
    - OverloadedRecordDot

benchmarks:
  generic-inference-benchmark:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - generic-inference
    default-extensions:
    - DuplicateRecordFields
    - NoFieldSelectors
    - OverloadedRecordDot
